USE [master]
GO

/****** Object:  Database [N5Now]    Script Date: 02/02/2024 15:19:50 ******/
CREATE DATABASE [N5Now]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'N5Now', FILENAME = N'C:\Users\mregalado\N5Now.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'N5Now_log', FILENAME = N'C:\Users\mregalado\N5Now_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [N5Now].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [N5Now] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [N5Now] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [N5Now] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [N5Now] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [N5Now] SET ARITHABORT OFF 
GO

ALTER DATABASE [N5Now] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [N5Now] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [N5Now] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [N5Now] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [N5Now] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [N5Now] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [N5Now] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [N5Now] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [N5Now] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [N5Now] SET  DISABLE_BROKER 
GO

ALTER DATABASE [N5Now] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [N5Now] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [N5Now] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [N5Now] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [N5Now] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [N5Now] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [N5Now] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [N5Now] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [N5Now] SET  MULTI_USER 
GO

ALTER DATABASE [N5Now] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [N5Now] SET DB_CHAINING OFF 
GO

ALTER DATABASE [N5Now] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [N5Now] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [N5Now] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [N5Now] SET QUERY_STORE = OFF
GO

USE [N5Now]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [N5Now] SET  READ_WRITE 
GO


